//! `bdp generate` command implementation
//!
//! Generates workflow integration files for Python, Snakemake, and Nextflow
//! based on the project lockfile and cache configuration.

use std::path::{Path, PathBuf};

use colored::Colorize;

use crate::{error::Result, lockfile::Lockfile, manifest::parse_source_spec, project};

/// Resolved source info for code generation
struct SourceInfo {
    /// Variable name (e.g., UNIPROT_P01308_FASTA)
    var_name: String,
    /// Original spec string
    spec: String,
    /// Relative file path from project root
    rel_path: String,
}

/// Generate Python data paths module (bdp_data.py)
pub async fn python() -> Result<()> {
    let project_root = project::find_project_root()?;
    let sources = collect_sources(&project_root)?;

    if sources.is_empty() {
        println!("No sources found in lockfile. Run 'bdp pull' first.");
        return Ok(());
    }

    let mut output = String::new();
    output.push_str(
        "\"\"\"BDP data paths - auto-generated by 'bdp generate python'. Do not edit.\"\"\"\n",
    );
    output.push_str("from pathlib import Path\n");
    output.push('\n');
    output.push_str("_BASE = Path(__file__).parent\n");

    for src in &sources {
        output.push('\n');
        output.push_str(&format!("# Source: {}\n", src.spec));
        // Build path segments for Path() chaining
        let segments = path_to_python_segments(&src.rel_path);
        output.push_str(&format!("{} = _BASE / {}\n", src.var_name, segments));
    }

    let output_path = project_root.join("bdp_data.py");
    std::fs::write(&output_path, &output)?;

    println!("{} Generated: bdp_data.py ({} source(s))", "✓".green(), sources.len());

    Ok(())
}

/// Generate Snakemake config file (config/bdp_data.yaml)
pub async fn snakemake() -> Result<()> {
    let project_root = project::find_project_root()?;
    let sources = collect_sources(&project_root)?;

    if sources.is_empty() {
        println!("No sources found in lockfile. Run 'bdp pull' first.");
        return Ok(());
    }

    let mut output = String::new();
    output
        .push_str("# BDP data paths - auto-generated by 'bdp generate snakemake'. Do not edit.\n");
    output.push_str("# Include in Snakefile: configfile: \"config/bdp_data.yaml\"\n");
    output.push_str("bdp:\n");

    for src in &sources {
        let key = src.var_name.to_lowercase();
        // Use forward slashes for portability
        let path = src.rel_path.replace('\\', "/");
        output.push_str(&format!("  {}: \"{}\"\n", key, path));
    }

    let config_dir = project_root.join("config");
    std::fs::create_dir_all(&config_dir)?;
    let output_path = config_dir.join("bdp_data.yaml");
    std::fs::write(&output_path, &output)?;

    println!("{} Generated: config/bdp_data.yaml ({} source(s))", "✓".green(), sources.len());

    Ok(())
}

/// Generate Nextflow config file (conf/bdp_data.config)
pub async fn nextflow() -> Result<()> {
    let project_root = project::find_project_root()?;
    let sources = collect_sources(&project_root)?;

    if sources.is_empty() {
        println!("No sources found in lockfile. Run 'bdp pull' first.");
        return Ok(());
    }

    let mut output = String::new();
    output
        .push_str("// BDP data paths - auto-generated by 'bdp generate nextflow'. Do not edit.\n");
    output.push_str("// Include in nextflow.config: includeConfig 'conf/bdp_data.config'\n");
    output.push_str("params {\n");
    output.push_str("    bdp {\n");

    for src in &sources {
        let key = src.var_name.to_lowercase();
        // Use forward slashes and Nextflow's projectDir variable
        let path = src.rel_path.replace('\\', "/");
        output.push_str(&format!("        {} = \"${{projectDir}}/{}\"\n", key, path));
    }

    output.push_str("    }\n");
    output.push_str("}\n");

    let conf_dir = project_root.join("conf");
    std::fs::create_dir_all(&conf_dir)?;
    let output_path = conf_dir.join("bdp_data.config");
    std::fs::write(&output_path, &output)?;

    println!("{} Generated: conf/bdp_data.config ({} source(s))", "✓".green(), sources.len());

    Ok(())
}

/// Collect source information from lockfile and project config
fn collect_sources(project_root: &Path) -> Result<Vec<SourceInfo>> {
    let lockfile_path = project_root.join("bdp.lock");
    if !lockfile_path.exists() {
        return Ok(Vec::new());
    }

    let lockfile = Lockfile::load(&lockfile_path)?;
    let config = crate::project::ProjectConfig::load(project_root)?;
    let cache_path_str = &config.cache.path;

    let mut sources = Vec::new();

    // Sort specs for deterministic output
    let mut specs: Vec<&String> = lockfile.sources.keys().collect();
    specs.sort();

    for spec in specs {
        let entry = match lockfile.sources.get(spec.as_str()) {
            Some(e) => e,
            None => continue,
        };

        let var_name = spec_to_var_name(spec);
        let rel_path = spec_to_file_path(spec, &entry.format, cache_path_str)?;

        sources.push(SourceInfo {
            var_name,
            spec: spec.clone(),
            rel_path,
        });
    }

    Ok(sources)
}

/// Convert a source spec to a variable name.
///
/// `uniprot:P01308-fasta@1.0` → `UNIPROT_P01308_FASTA`
///
/// Always includes the org prefix to avoid ambiguity across registries.
fn spec_to_var_name(spec: &str) -> String {
    // Parse spec: registry:identifier-format@version
    let parts: Vec<&str> = spec.split(':').collect();
    if parts.len() != 2 {
        // Fallback: sanitize the whole spec
        return sanitize_for_var(spec);
    }

    let org = parts[0];
    let rest = parts[1];

    // Split at @ to remove version
    let name_part = rest.split('@').next().unwrap_or(rest);

    // Replace hyphens with underscores and uppercase
    let combined = format!("{}_{}", org, name_part);
    sanitize_for_var(&combined)
}

/// Sanitize a string into a valid uppercase variable name
fn sanitize_for_var(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect()
}

/// Convert a source spec to a relative file path within the cache directory.
///
/// `uniprot:P01308-fasta@1.0` with cache `.bdp/data` →
/// `.bdp/data/sources/uniprot/P01308/1.0/P01308_1.0.fasta`
fn spec_to_file_path(spec: &str, format: &str, cache_path: &str) -> Result<String> {
    let (org, name, version, _fmt) = parse_source_spec(spec)?;
    let version_clean = version.split('-').next().unwrap_or(&version);
    let filename = format!("{}_{}.{}", name, version_clean, format);

    let path = PathBuf::from(cache_path)
        .join("sources")
        .join(&org)
        .join(&name)
        .join(version_clean)
        .join(&filename);

    // Always use forward slashes for cross-platform compatibility
    Ok(path.to_string_lossy().replace('\\', "/"))
}

/// Convert a relative path to Python Path() chained segments.
/// `.bdp/data/sources/uniprot/P01308/1.0/P01308_1.0.fasta` →
/// `".bdp" / "data" / "sources" / "uniprot" / "P01308" / "1.0" /
/// "P01308_1.0.fasta"`
fn path_to_python_segments(rel_path: &str) -> String {
    let parts: Vec<&str> = rel_path.split('/').collect();
    parts
        .iter()
        .map(|p| format!("\"{}\"", p))
        .collect::<Vec<_>>()
        .join(" / ")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_spec_to_var_name_with_format() {
        assert_eq!(spec_to_var_name("uniprot:P01308-fasta@1.0"), "UNIPROT_P01308_FASTA");
    }

    #[test]
    fn test_spec_to_var_name_without_format() {
        assert_eq!(spec_to_var_name("ncbi:blast@2.14.0"), "NCBI_BLAST");
    }

    #[test]
    fn test_spec_to_var_name_complex() {
        assert_eq!(spec_to_var_name("ensembl:homo_sapiens-gtf@110"), "ENSEMBL_HOMO_SAPIENS_GTF");
    }

    #[test]
    fn test_spec_to_file_path() {
        let result = spec_to_file_path("uniprot:P01308-fasta@1.0", "fasta", ".bdp/data").unwrap();
        assert_eq!(result, ".bdp/data/sources/uniprot/P01308/1.0/P01308_1.0.fasta");
    }

    #[test]
    fn test_path_to_python_segments() {
        let result =
            path_to_python_segments(".bdp/data/sources/uniprot/P01308/1.0/P01308_1.0.fasta");
        assert_eq!(
            result,
            "\".bdp\" / \"data\" / \"sources\" / \"uniprot\" / \"P01308\" / \"1.0\" / \
             \"P01308_1.0.fasta\""
        );
    }

    #[test]
    fn test_sanitize_for_var() {
        assert_eq!(sanitize_for_var("hello-world"), "HELLO_WORLD");
        assert_eq!(sanitize_for_var("test.123"), "TEST_123");
    }

    #[test]
    fn test_collect_sources_no_lockfile() {
        let temp = tempfile::TempDir::new().unwrap();
        let result = collect_sources(temp.path()).unwrap();
        assert!(result.is_empty());
    }
}
