# =============================================================================
# Outputs - Connection information for the application
# =============================================================================

# Instance Information
output "instance_ip" {
  description = "Public IP address of the BDP server"
  value       = openstack_compute_instance_v2.bdp_server.access_ip_v4
}

output "instance_id" {
  description = "Instance ID"
  value       = openstack_compute_instance_v2.bdp_server.id
}

output "ssh_command" {
  description = "SSH command to connect to the instance"
  value       = "ssh ubuntu@${openstack_compute_instance_v2.bdp_server.access_ip_v4}"
}

# Database Information
output "database_host" {
  description = "PostgreSQL host"
  value       = ovh_cloud_project_database.postgresql.endpoints[0].domain
  sensitive   = false
}

output "database_port" {
  description = "PostgreSQL port"
  value       = ovh_cloud_project_database.postgresql.endpoints[0].port
}

output "database_uri" {
  description = "PostgreSQL connection URI (without password)"
  value       = "postgresql://${var.db_user}@${ovh_cloud_project_database.postgresql.endpoints[0].domain}:${ovh_cloud_project_database.postgresql.endpoints[0].port}/${var.db_name}?sslmode=require"
  sensitive   = false
}

output "database_password" {
  description = "PostgreSQL user password"
  value       = ovh_cloud_project_database_user.bdp_user.password
  sensitive   = true
}

# S3 Storage Information
output "s3_endpoint" {
  description = "S3 endpoint URL"
  value       = local.s3_endpoint
}

output "s3_bucket" {
  description = "S3 bucket name"
  value       = var.storage_bucket_name
}

output "s3_access_key" {
  description = "S3 access key"
  value       = ovh_cloud_project_user_s3_credential.s3_creds.access_key_id
  sensitive   = true
}

output "s3_secret_key" {
  description = "S3 secret key"
  value       = ovh_cloud_project_user_s3_credential.s3_creds.secret_access_key
  sensitive   = true
}

output "s3_region" {
  description = "S3 region"
  value       = var.storage_region
}

# Application Environment Variables
output "env_file_content" {
  description = "Environment variables for the application (.env format)"
  sensitive   = true
  value       = <<-EOF
    # BDP Production Environment - Generated by Terraform
    # Instance: ${openstack_compute_instance_v2.bdp_server.access_ip_v4}

    # Server Configuration
    SERVER_HOST=0.0.0.0
    SERVER_PORT=8000
    RUST_LOG=info,bdp_server=info,sqlx=warn

    # Database Configuration
    DATABASE_URL=postgresql://${var.db_user}:${ovh_cloud_project_database_user.bdp_user.password}@${ovh_cloud_project_database.postgresql.endpoints[0].domain}:${ovh_cloud_project_database.postgresql.endpoints[0].port}/${var.db_name}?sslmode=require
    DATABASE_MAX_CONNECTIONS=10

    # S3 Storage Configuration
    STORAGE_TYPE=s3
    STORAGE_S3_ENDPOINT=${local.s3_endpoint}
    STORAGE_S3_REGION=${var.storage_region}
    STORAGE_S3_BUCKET=${var.storage_bucket_name}
    STORAGE_S3_ACCESS_KEY=${ovh_cloud_project_user_s3_credential.s3_creds.access_key_id}
    STORAGE_S3_SECRET_KEY=${ovh_cloud_project_user_s3_credential.s3_creds.secret_access_key}
    STORAGE_S3_PATH_STYLE=false

    # API Configuration
    API_BASE_URL=http://${openstack_compute_instance_v2.bdp_server.access_ip_v4}:8000
    CORS_ORIGINS=http://${openstack_compute_instance_v2.bdp_server.access_ip_v4}:3000,http://${openstack_compute_instance_v2.bdp_server.access_ip_v4}:8000

    # Ingestion (disabled by default in production)
    INGEST_ENABLED=false
  EOF
}
